# .github/workflows/ci.yml
name: CI/CD — frontend

on:
  push:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint (ESLint)
        run: npm run lint

      - name: Run unit tests (Vitest)
        run: npm run test

  CD:
    runs-on: ubuntu-latest
    needs: CI
    if: github.ref == 'refs/heads/main' # only run on main branch
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/proabdallami/portfolio:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: connect to the server using Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          ping: ${{ secrets.HOST_ADDRESS }}

      - name: Deploy to the server
        run: tailscale ssh ${{ secrets.HOST_USER }}@${{ secrets.HOST_ADDRESS }} "cd ${{ secrets.PROJECT_DIRECTORY }} && docker compose up -d --pull always"
